CentOS coreutils doesn't provide realpath; include readlink --canonicalize alternative.

diff --git a/editautxt b/editautxt
--- a/editautxt
+++ b/editautxt
@@ -32,8 +32,10 @@ if which realpath &> /dev/null ; then
   REALPATH=realpath
 elif which grealpath &> /dev/null ; then
   REALPATH=grealpath
+elif which readlink &> /dev/null ; then
+  REALPATH=readline --canonicalize
 else
-  echo "${0}: realpath (or grealpath) not found" >&2
+  echo "${0}: realpath (or grealpath, or readlink) not found" >&2
   exit 1
 fi
 
